# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    name='arcade-generator',
    version='0.10.2',
    description='A static site generator',
    python_requires='==3.*,>=3.6.0',
    author='Yabir Benchakhtir',
    author_email='yabirg@protonmail.com',
    license='MIT',
    classifiers=[
        'Environment :: Console', 'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent', 'Topic :: Internet :: WWW/HTTP'
    ],
    entry_points={"console_scripts": ["arcade = arcade_generator.main:cli"]},
    packages=['arcade_generator'],
    package_dir={"": "."},
    package_data={
        "arcade_generator": [
            "*.md~", "*.py~", ".pytest_cache/*.TAG", ".pytest_cache/*.md"
        ]
    },
    install_requires=[
        'click==7.*,>=7.1.1', 'jinja2', 'livereload==2.*,>=2.6.1',
        'markdown==3.*,>=3.2.1', 'pyyaml==5.*,>=5.3.1'
    ],
)
